version: "3.7"

services:
  db:
    container_name: thecodeofthings_db
    image: postgres:10.9
    hostname: db
    env_file: development.env
    ports:
      - "5432"
    volumes:
      - ./data/:/var/lib/postgresql/data/pgdata

  django:
    container_name: thecodeofthings_django
    build:
      context: "./thecodeofthings"
      args:
        IS_LOCAL_ENV: "true"
    hostname: django
    env_file: development.env
    volumes:
      - ./thecodeofthings:/code
      - ./thecodeofthings/media:/media
    links:
      - db
    depends_on:
      - db
    entrypoint: /entrypoint.sh
    command: ./scripts/development.sh
    ports:
      - "8000:8000"
