# Generated by Django 3.2.11 on 2022-01-30 03:46

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0023_add_choose_permissions"),
        ("blog", "0001_initial"),
        ("wagtailcore", "0066_collection_management_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("hidden", models.BooleanField(blank=True, default=False)),
                ("research", models.BooleanField(blank=True, default=False)),
            ],
            options={
                "ordering": ["category__order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Creator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(blank=True, max_length=200)),
                ("last_name", models.CharField(blank=True, max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=400, unique=True)),
            ],
            options={
                "ordering": ("last_name", "first_name"),
            },
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                ("key", models.CharField(max_length=20, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("artwork", "Artwork"),
                            ("audioRecording", "Audio Recording"),
                            ("bill", "Bill"),
                            ("blogPost", "Blog Post"),
                            ("book", "Book"),
                            ("bookSection", "Book Section"),
                            ("case", "Case"),
                            ("computerProgram", "Computer Program"),
                            ("conferencePaper", "Conference Paper"),
                            ("dictionaryEntry", "Dictionary Entry"),
                            ("document", "Document"),
                            ("email", "E-mail"),
                            ("encyclopediaArticle", "Encyclopedia Article"),
                            ("film", "Film"),
                            ("forumPost", "Forum Post"),
                            ("hearing", "Hearing"),
                            ("instantMessage", "Instant Message"),
                            ("interview", "Interview"),
                            ("journalArticle", "Journal Article"),
                            ("letter", "Letter"),
                            ("magazineArticle", "Magazine Article"),
                            ("manuscript", "Manuscript"),
                            ("map", "Map"),
                            ("newspaperArticle", "Newspaper Article"),
                            ("patent", "Patent"),
                            ("podcast", "Podcast"),
                            ("presentation", "Presentation"),
                            ("radioBroadcast", "Radio Broadcast"),
                            ("report", "Report"),
                            ("statute", "Statute"),
                            ("tvBroadcast", "TV Broadcast"),
                            ("thesis", "Thesis"),
                            ("videoRecording", "Video Recording"),
                            ("webpage", "Web Page"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("short_title", models.CharField(blank=True, max_length=200)),
                ("abstract_note", models.TextField(blank=True)),
                ("date", models.CharField(blank=True, max_length=200)),
                ("url", models.URLField(blank=True)),
                ("date_added", models.DateTimeField(blank=True, null=True)),
                ("date_modified", models.DateTimeField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=20)),
                ("rights", models.CharField(blank=True, max_length=200)),
                ("extra", models.TextField(blank=True)),
                ("additional", models.JSONField(blank=True, null=True)),
                ("collections", models.ManyToManyField(blank=True, to="references.Collection")),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=20)),
                ("creator", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="references.creator")),
                (
                    "reference",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="references.reference"),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ReferenceIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("date_created", models.DateTimeField()),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, "wagtailcore.page"),
        ),
        migrations.AddField(
            model_name="reference",
            name="creators",
            field=models.ManyToManyField(blank=True, through="references.Role", to="references.Creator"),
        ),
        migrations.AddConstraint(
            model_name="creator",
            constraint=models.UniqueConstraint(fields=("first_name", "last_name"), name="unique_creator_name"),
        ),
        migrations.AddField(
            model_name="collection",
            name="category",
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to="blog.category"),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("creator", "reference", "title"), name="unique_creator_reference_title"
            ),
        ),
    ]
