# Generated by Django 3.2.11 on 2022-01-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="referenceindexpage",
            name="research",
            field=models.BooleanField(default=False),
        ),
    ]
