# Generated by Django 3.2.10 on 2022-01-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Line",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=500)),
                ("is_published", models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(max_length=300)),
                ("quote", models.TextField()),
                ("citation", models.CharField(max_length=300)),
                ("is_published", models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
