# Generated by Django 3.2.10 on 2022-01-03 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0066_collection_management_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagtailimages", "0023_add_choose_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=100, unique=True),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="PoemPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("description", wagtail.core.fields.RichTextField(blank=True)),
                ("date_created", models.DateTimeField()),
                ("date_modified", models.DateTimeField()),
                ("repository", models.URLField(blank=True)),
                (
                    "versions",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "version",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        ("title", wagtail.core.blocks.CharBlock()),
                                        (
                                            "description",
                                            wagtail.core.blocks.RichTextBlock(),
                                        ),
                                        (
                                            "featured_image",
                                            wagtail.images.blocks.ImageChooserBlock(required=False),
                                        ),
                                        (
                                            "date_created",
                                            wagtail.core.blocks.DateTimeBlock(),
                                        ),
                                        (
                                            "date_released",
                                            wagtail.core.blocks.DateTimeBlock(required=False),
                                        ),
                                        (
                                            "date_modified",
                                            wagtail.core.blocks.DateTimeBlock(required=False),
                                        ),
                                        (
                                            "link",
                                            wagtail.core.blocks.URLBlock(required=False),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                    ),
                ),
                (
                    "authors",
                    modelcluster.fields.ParentalManyToManyField(to=settings.AUTH_USER_MODEL),
                ),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "mediums",
                    modelcluster.fields.ParentalManyToManyField(blank=True, to="poems.Medium"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PoemIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("date_created", models.DateTimeField()),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
